export const FETCH_MY_VACANCIES = 'FETCH_MY_VACANCIES';
export const FETCH_MY_VACANCIES_SUCCESS = 'FETCH_MY_VACANCIES_SUCCESS';
export const FETCH_MY_VACANCIES_FAIL = 'FETCH_MY_VACANCIES_FAIL';

export const FETCH_VACANCY = 'FETCH_VACANCY';
export const FETCH_VACANCY_SUCCESS = 'FETCH_VACANCY_SUCCESS';
export const FETCH_VACANCY_FAIL = 'FETCH_VACANCY_FAIL';

export const UPDATE_VACANCY_ACTIVITY = 'UPDATE_VACANCY_ACTIVITY';
export const UPDATE_VACANCY_ACTIVITY_SUCCESS = 'UPDATE_VACANCY_ACTIVITY_SUCCESS';
export const UPDATE_VACANCY_ACTIVITY_FAIL = 'UPDATE_VACANCY_ACTIVITY_FAIL';

export const CREATE_VACANCY = 'CREATE_VACANCY';
export const CREATE_VACANCY_SUCCESS = 'CREATE_VACANCY_SUCCESS';
export const CREATE_VACANCY_FAIL = 'CREATE_VACANCY_FAIL';

export const DELETE_VACANCY = 'DELETE_VACANCY';
export const DELETE_VACANCY_SUCCESS = 'DELETE_VACANCY_SUCCESS';
export const DELETE_VACANCY_FAIL = 'DELETE_VACANCY_FAIL';

export const COPY_VACANCY = 'COPY_VACANCY';
export const COPY_VACANCY_SUCCESS = 'COPY_VACANCY_SUCCESS';
export const COPY_VACANCY_FAIL = 'COPY_VACANCY_FAIL';

export const FETCH_SCOPE_ACTIVITY = 'FETCH_SCOPE_ACTIVITY';
export const FETCH_SCOPE_ACTIVITY_SUCCESS = 'FETCH_SCOPE_ACTIVITY_SUCCESS';

export const UPDATE_VACANCY_TITLEBOX = 'UPDATE_VACANCY_TITLEBOX';
export const UPDATE_VACANCY_TITLEBOX_SUCCESS = 'UPDATE_VACANCY_TITLEBOX_SUCCESS';
export const UPDATE_VACANCY_TITLEBOX_FAIL = 'UPDATE_VACANCY_TITLEBOX_FAIL';

export const UPDATE_VACANCY_LANGUAGES = 'UPDATE_VACANCY_LANGUAGES';
export const UPDATE_VACANCY_LANGUAGES_SUCCESS = 'UPDATE_VACANCY_LANGUAGES_SUCCESS';
export const UPDATE_VACANCY_LANGUAGES_FAIL = 'UPDATE_VACANCY_LANGUAGES_FAIL';

export const UPDATE_VACANCY_ABOUT = 'UPDATE_VACANCY_ABOUT';
export const UPDATE_VACANCY_ABOUT_SUCCESS = 'UPDATE_VACANCY_ABOUT_SUCCESS';
export const UPDATE_VACANCY_ABOUT_FAIL = 'UPDATE_VACANCY_ABOUT_FAIL';

export const UPDATE_VACANCY_LOGO = 'UPDATE_VACANCY_LOGO';
export const UPDATE_VACANCY_LOGO_SUCCESS = 'UPDATE_VACANCY_LOGO_SUCCESS';
export const UPDATE_VACANCY_LOGO_FAIL = 'UPDATE_VACANCY_LOGO_FAIL';

export const UPDATE_VACANCY_SKILLS = 'UPDATE_VACANCY_SKILLS';
export const UPDATE_VACANCY_SKILLS_SUCCESS = 'UPDATE_VACANCY_SKILLS_SUCCESS';
export const UPDATE_VACANCY_SKILLS_FAIL = 'UPDATE_VACANCY_SKILLS_FAIL';

export const UPDATE_VACANCY_COURSES = 'UPDATE_VACANCY_COURSES';
export const UPDATE_VACANCY_COURSES_SUCCESS = 'UPDATE_VACANCY_COURSES_SUCCESS';
export const UPDATE_VACANCY_COURSES_FAIL = 'UPDATE_VACANCY_COURSES_FAIL';

export const UPDATE_VACANCY_CERTIFICATES = 'UPDATE_VACANCY_CERTIFICATES';
export const UPDATE_VACANCY_CERTIFICATES_SUCCESS = 'UPDATE_VACANCY_CERTIFICATES_SUCCESS';
export const UPDATE_VACANCY_CERTIFICATES_FAIL = 'UPDATE_VACANCY_CERTIFICATES_FAIL';

export const UPDATE_VACANCY_CONDITIONS = 'UPDATE_VACANCY_CONDITIONS';
export const UPDATE_VACANCY_CONDITIONS_SUCCESS = 'UPDATE_VACANCY_CONDITIONS_SUCCESS';
export const UPDATE_VACANCY_CONDITIONS_FAIL = 'UPDATE_VACANCY_CONDITIONS_FAIL';

export const FETCH_TIME_SCHEDULES = 'FETCH_TIME_SCHEDULES';
export const FETCH_TIME_SCHEDULES_SUCCESS = 'FETCH_TIME_SCHEDULES_SUCCESS';

export const FETCH_VACANCY_ADVANTAGES = 'FETCH_VACANCY_ADVANTAGES';
export const FETCH_VACANCY_ADVANTAGES_SUCCESS = 'FETCH_VACANCY_ADVANTAGES_SUCCESS';