export const SEARCH_CVS = 'SEARCH_CVS';
export const SEARCH_CVS_SUCCESS = 'SEARCH_CVS_SUCCESS';
export const SEARCH_CVS_FAIL = 'SEARCH_CVS_FAIL';

export const SEARCH_VACANCIES = 'SEARCH_VACANCIES';
export const SEARCH_VACANCIES_SUCCESS = 'SEARCH_VACANCIES_SUCCESS';
export const SEARCH_VACANCIES_FAIL = 'SEARCH_VACANCIES_FAIL';

export const GET_VACANCY = 'GET_VACANCY';
export const GET_VACANCY_SUCCESS = 'GET_VACANCY_SUCCESS';
export const GET_VACANCY_FAIL = 'GET_VACANCY_FAIL';

export const GET_CV = 'GET_CV';
export const GET_CV_SUCCESS = 'GET_CV_SUCCESS';
export const GET_CV_FAIL = 'GET_CV_FAIL';
